### PR TITLE
Remove false positives

### PR DESCRIPTION
**Pull request by p1r473**
Please remove gateway.reddit.com
This breaks viewing user activity on Reddit

Additionally, you should enable people to create "issues" in this repo, so we can report problems with your list, without having to create a pull request.

### CODE REVIEW

**Comment by p1r473** [comment]
pmd.cdn.turner.com breaks CNN videos

also please enable Issues on your Git so these false positives can be reported without pull requests

**Comment by p1r473** [comment]
ht.cdn.turner.com breaks embedded CNN videos in the Google news app

**Comment by p1r473** [comment]
forms.gle is just Google Forms and should not be blocked

**Comment by p1r473** [comment]
accounts.us1.gigya.com
socialize.us1.gigya.com

These domains break logging into iRobot app on Andoird

**Comment by p1r473** [comment]
Hello,
The following domains break citynews1130 videos:

secure.brightcove.com
players.brightcove.net
edge.api.brightcove.com

**Comment by p1r473** [comment]
dyjpb62732.i.lithium.com
Non malicious
Breaks github.community site layout

**Comment by 10ZiN** [comment]
Files in the downloads folder, whilst publicly accessible, are not designed for public consumption and may not be suitable for your particular use-case. It's recommended to modify your local copy accordingly to suit your needs.

For example, you could create a text-based file with your domain exclusions, and parse hosts.txt like this:

`grep -F -x -v -f whitelist.txt hosts.txt | sort -u > whitelisted_hosts.txt`

**Comment by 10ZiN** [comment]
Files in the downloads folder, whilst publicly accessible, are not designed for public consumption and may not be suitable for your particular use-case (as stated in `README.md`).

It's recommended to modify your local copy accordingly to suit your needs. For example, you could create a text-based file with your domain exclusions, and parse hosts.txt like this:

`grep -F -x -v -f whitelist.txt hosts.txt | sort -u > whitelisted_hosts.txt`

Where `whitelist.txt` has the following layout:
```
    0.0.0.0 excluded.domain.tld
    0.0.0.0 www.domain.tld
    0.0.0.0 domain.tld
    0.0.0.0 etc.domain.tld
```

**Comment by 10ZiN** [comment]
Files in the downloads folder, whilst publicly accessible, are not designed for public consumption and may not be suitable for your particular use-case (as stated in `README.md` and why Issues is disabled).

It's recommended to modify your local copy accordingly to suit your needs. For example, you could create a text-based file with your domain exclusions, and parse hosts.txt like this:

`grep -F -x -v -f whitelist.txt hosts.txt | sort -u > whitelisted_hosts.txt`

Where `whitelist.txt` has the following layout:
```
excluded.domain.tld
www.domain.tld
domain.tld
etc.domain.tld
```

**Pull request closed without merging**
